# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 973789da6bb261d9ed66873f8439fc7ee4ac33051c488885e8c2e1335295787ada0c7b5aaa7f707fb988349bb5758c8e4da5ddbcb41b0dbe2ecc2e807a56de29

test:
  secret_key_base: 42894324de3ba75563588ddeb0a93bb906029d6ec896a15bfb4aeeb3f9f562f1a5531e43d9aaecf8a7d4585fdbd24d45997109b3649cb484324682e2f7c8240b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
